name = "BetaKDE"
uuid = "510de360-7fee-4af5-ad83-2adfbc793e05"
version = "0.1.0"
authors = ["Johan Hallberg Szabadvary"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extensions]
BetaKDEDensityInterfaceExt = "DensityInterface"
BetaKDEStatsBaseExt = "StatsBase"

[compat]
DensityInterface = "0.4"
Distributions = "0.25"
RecipesBase = "1"
SpecialFunctions = "2"
Statistics = "1"
StatsBase = "0.33, 0.34"
julia = "1.10"

[extras]
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StatsBase", "DensityInterface"]
